broker: zerodha
api_keys:
  api_key: "your_api_key"
  api_secret: "your_api_secret"
news_api_keys:
  newsapi: "91e7ad7f30d3492ba1090af68258f755"
alpha_vantage_api_key: "QUQ4JVOG6VXMUIXT"
stocks:
  - "RELIANCE.NSE"
  - "TCS.NSE"
  - "AAPL"
risk:
  max_position: 0.1
  stop_loss_pct: 0.02
capital: 100000
run_interval: 300
log_path: "./trades_log.csv"
start_date: "2024-01-01" # Optional: for historical fetch
end_date: "2025-01-01" # Optional: for historical fetch
