broker: zerodha
api_keys:
  api_key: "your_api_key"
  api_secret: "your_api_secret"
news_api_keys:
  newsapi: "your_news_api_key"
stocks:
  - "RELIANCE.NS"
  - "TCS.NS"
  - "HDFCBANK.NS"
risk:
  max_position: 0.1
  stop_loss_pct: 0.02
capital: 100000
run_interval: 300
log_path: "./trades_log.csv"
